---
- name: Install curl and Docker
  hosts: all
  become: true
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Run Docker installation script
      command: curl -sSL https://get.docker.com/ | sh
